version: '2'
services:
  apache-php:
    #build: ./apache_php
    image: php:7.0.8-apache
    command: apache2-foreground
    ports:
      - "8870:80"
    volumes:
      - ./project:/var/www/html:ro
  fastcgi-php:
    image: php:7.0.8-fpm
    #image: php:7.0.8-fpm-alpine
    command: php-fpm
    ports:
      - "9123:9000"
    volumes:
      - ./project:/var/www/html:ro
  nginx-server:
    #build: ./nginx
    #image: nginx:mainline-alpine
    image: nginx:latest
    command: nginx -g 'daemon off;'
    volumes:
      - ./project:/usr/share/nginx/html:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
##    #expose:
##    #   - 80
    ports:
      - "8880:80"
    links:
      - fastcgi-php:fastcgi-php